FROM node:latest

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global


RUN mkdir -p  /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN apt-get install git
RUN rm -rf package-lock.json node_modules
RUN npm install


CMD ["npm", "start"]