FROM node:latest

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN mkdir -p  /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN rm -rf package-lock.json node_modules
RUN npm install
RUN apk update && apk add git
CMD ["npm", "start"]