module.exports = Object.freeze({

    //NAME CONSTANTS
    APPLICATION_NAME: "Estudio",

    //APPLICATION URL'S
        APPLICATION_FRONT_BASE_URL:  process.env.REACT_APP_APPLICATION_FRONT_BASE_URL, //APPLICATION FRONT BASE URL
        APPLICATION_SERVER_API_BASE_URL: process.env.REACT_APP_APPLICATION_SERVER_API_BASE_URL,
        APPLICATION_RESET_PASSWORD_URL: process.env.REACT_APP_APPLICATION_RESET_PASSWORD_URL,

    //ROUTES
        INITIAL_PAGE_URL: process.env.REACT_APP_INITIAL_PAGE_URL, //Application Login and Initial page
        ESTUDIO_PAGE_URL: process.env.REACT_APP_ESTUDIO_PAGE_URL, //Application Estudio Page
        DASHBOARD_PAGE_URL: process.env.REACT_APP_DASHBOARD_PAGE_URL, //Application Dashboard page
        DASHBOARD_BASE_URL: process.env.REACT_APP_DASHBOARD_BASE_URL,

    //API'S CAMARA DOS DEPUTADOS
        API_CD_EVENTOS_PLENARIO: process.env.REACT_APP_API_CD_EVENTOS_PLENARIO,// 110 code corresponds to Plenary
        API_CD_EVENTOS: process.env.REACT_APP_API_CD_EVENTOS,
        API_CD_ORIENTACAO_VOTACAO: process.env.REACT_APP_API_CD_ORIENTACAO_VOTACAO,
        API_CD_NOMINAL_VOTACAO: process.env.REACT_APP_API_CD_NOMINAL_VOTACAO,
        API_CD_ITENS_EM_VOTACAO: process.env.REACT_APP_API_CD_ITENS_EM_VOTACAO,
        API_CD_PRESENCA_VOTACAO_PLENARIO: process.env.REACT_APP_API_CD_PRESENCA_VOTACAO_PLENARIO,
        API_CD_PAUTA_SESSAO_PLENARIO: process.env.REACT_APP_API_CD_PAUTA_SESSAO_PLENARIO,
        API_CD_VOTACAO_ITEM: process.env.REACT_APP_API_CD_VOTACAO_ITEM,

    //URL's
        ACOMPANHE_PORTAL_URL_PAGE: process.env.REACT_APP_ACOMPANHE_PORTAL_URL_PAGE,
        PROPOSICAO_INFO_PAGE: process.env.REACT_APP_PROPOSICAO_INFO_PAGE,
        

    //API'S BACKEND
        //AUTH URL'S
            TOKEN_REFRESH_URL: process.env.REACT_APP_TOKEN_REFRESH_URL, //Application Api Token REFRESH PATH
            TOKEN_OBTAIN_URL: process.env.REACT_APP_TOKEN_OBTAIN_URL, //Application Api Token PATH
            TOKEN_VERIFY_URL: process.env.REACT_APP_TOKEN_VERIFY_URL, //Application Api Token Verify

        //FILE-VIDEO
            API_FILE_VIDEO_URL:process.env.REACT_APP_API_FILE_VIDEO_URL, //Application end-point to obtain the source of specific video

        //NEWS
            API_NEWS_URL:process.env.REACT_APP_API_NEWS_URL, //Obtain news list
            API_NEWS_SEARCH_URL:process.env.REACT_APP_API_NEWS_SEARCH_URL, //Obtain specific news using parameters

        //PUBLICATIONS
            API_PUBLICATIONS_URL:process.env.REACT_APP_API_PUBLICATIONS_URL,
        //RADIO AGENCY
            API_RADIO_AGENCY_URL:process.env.REACT_APP_API_RADIO_AGENCY_URL,
            API_RADIO_AGENCY_SEARCH_URL:process.env.REACT_APP_API_RADIO_AGENCY_SEARCH_URL,

        //RADIO CAMARA
            API_RADIO_CAMARA_URL:process.env.REACT_APP_API_RADIO_CAMARA_URL,
            API_RADIO_CAMARA_SEARCH_URL:process.env.REACT_APP_API_RADIO_CAMARA_SEARCH_URL,

        //SAVED CONTENTS
            API_SAVED_CONTENTS_URL:process.env.REACT_APP_API_SAVED_CONTENTS_URL,

        //SESSIONS
            API_SESSIONS_URL:process.env.REACT_APP_API_SESSIONS_URL,
            API_SESSIONS_URL_NOT_LIVE:process.env.REACT_APP_API_SESSIONS_URL_NOT_LIVE,
            API_SESSIONS_CURRENT_LIVE_URL:process.env.REACT_APP_API_SESSIONS_CURRENT_LIVE_URL,

        //TV CAMARA
            API_TV_CAMARA_URL:process.env.REACT_APP_API_TV_CAMARA_URL,
            API_TV_CAMARA_SEARCH_URL:process.env.REACT_APP_API_TV_CAMARA_SEARCH_URL,

        //VIDEOS
            API_VIDEOS_SNIPPETS:process.env.REACT_APP_API_VIDEOS_SNIPPETS,
  });
